// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "0dce51ff-6d25-459f-9ef1-1d9e842760ab";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onPulseSensorPinChange();
void onValorPulsoChange();

int BPM;
int pulseSensorPin;
int valorPulso;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(BPM, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(pulseSensorPin, READWRITE, ON_CHANGE, onPulseSensorPinChange);
  ArduinoCloud.addProperty(valorPulso, READWRITE, ON_CHANGE, onValorPulsoChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
